#!/bin/bash
echo -e "                |_|_|"
echo -e "          \_|||;;_/"
echo -e "             \d||%||%:b/"
echo -e "        \d~|dO%|i::b/"
echo -e "          ._H||dSf|||%::H_."
echo -e "          ._H@|dLF|}|;::H_."
echo -e "        ._H||dXFt||;.:H_."
echo -e "        ._?|{|P|||/;:.P_."
echo -e "         ._Hy||t|||;:H_."
echo -e "           ._?|x||T|;i:P_."
echo -e "            ._H||i||;:H_."
echo -e "            ._H|"|||;:H_."
echo -e "         .=================."
echo -e "         |;;|#H#|;;;;;;;;: |"
echo -e "         .=================."
echo -e "          |;|#H#|;;;;;;;: |"
echo -e "           |;|#H#|;;;;;: |"
echo -e "           |;|#H#|;;;;;: |"
echo -e "            |;|#H#|;;;: |"
echo -e "            |;|#H#|;;;: |"
echo -e "             |;|#H#|;: |"
echo -e "              ========="
